// housekeepfrontend/src/app/components/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class FooterComponent implements OnInit {

  constructor(private router: Router) { }

  ngOnInit(): void {
  }

  
  loggedin(){
    return sessionStorage.getItem('userEmail');
  }

  dashboard(){
    
    var flag =sessionStorage.getItem('flag');
    if(flag =='1')
      this.router.navigate(['admin/dashboard']);
    if(flag=='2')
      this.router.navigate(['technician/acceptance']);
  }

  logout(){
    sessionStorage.clear();
    this.router.navigate(['home']);
  }

}

<ul class="w-full py-2">
    <li><a routerLink="/home" >Home</a></li>
    <li><a routerLink="/contact" >Contact</a></li>
    <li><a routerLink="/about" >About</a></li>
    <li *ngIf="!loggedin()" style="float:right;"><a routerLink="/login">Login</a></li>
    <li *ngIf="!loggedin()" style="float:right;"><a routerLink="/register">Register</a></li>
    <li *ngIf="loggedin()" style="float:right;cursor:pointer;"><a (click)="dashboard()" >Dashboard</a></li>
    <li *ngIf="loggedin()" style="float:right;cursor:pointer;"><a (click)="logout()" >Logout</a></li>
    <h3 class="my-3 ml-10">v 1.0.0.0</h3>
    <h3 class="my-3 ml-10">Copyright:Immanual Jose</h3>
  </ul>

// housekeepReact/housekeep-react/src/navigation/footer.jsx
import { useNavigate } from 'react-router-dom';
export const Footer = () => {
  const navigate = useNavigate();
  const navigation = (url) => {
    navigate(url);
  };

  function loggedin() {
    return sessionStorage.getItem('authenticated');
  }
  return (
    <div>
      <div className='bg-black w-full flex'>
        <p
          className='text-white px-3 py-4  cursor-pointer text-sm'
          onClick={() => {
            navigation('/');
          }}
        >
          home
        </p>

        {loggedin() && (
          <p
            className='text-white px-3 py-4  cursor-pointer text-sm'
            onClick={() => {
              navigation('/profile');
            }}
          >
            profile
          </p>
        )}

        <div className='text-white py-4 text-sm ml-auto flex'>
          <p className='text-xl text-white'>©</p>
          <p className='text-xl  text-white'>immanual jose</p>
        </div>
        <p className='text-white py-4 text-sm ml-auto'>2017 - 2022</p>
        <p className='text-white py-4 text-sm ml-auto float-right px-4'>
          1.0.0
        </p>
      </div>
    </div>
  );
};
